# Generated by Django 3.2.9 on 2021-12-06 00:11

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True, blank=True)),
                ('first_name', models.CharField(max_length=30, unique=False)),
                ('last_name', models.CharField(max_length=30, unique=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='create at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='update at')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=core.models.get_default_profile_image, max_length=255, null=True, upload_to=core.models.get_profile_image_filepath)),
                ('hide_email', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
